/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package de.weinzierlstefan.expressionparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WITH = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int XOR = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int AS = 10;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 11;
  /** RegularExpression Id. */
  int HEX_LITERAL = 12;
  /** RegularExpression Id. */
  int HEX_DIGIT = 13;
  /** RegularExpression Id. */
  int REAL_LITERAL = 14;
  /** RegularExpression Id. */
  int EXPONENT = 15;
  /** RegularExpression Id. */
  int SIMPLE_STRING_LITERAL = 16;
  /** RegularExpression Id. */
  int DOUBLE_STRING_LITERAL = 17;
  /** RegularExpression Id. */
  int ESCAPED_CHAR = 18;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 19;
  /** RegularExpression Id. */
  int SIMPLE_ID = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int NOT_RBRACE = 23;
  /** RegularExpression Id. */
  int COMPLEX_ID = 24;
  /** RegularExpression Id. */
  int LPAREN = 25;
  /** RegularExpression Id. */
  int RPAREN = 26;
  /** RegularExpression Id. */
  int LBRACE = 27;
  /** RegularExpression Id. */
  int RBRACE = 28;
  /** RegularExpression Id. */
  int LBRACKET = 29;
  /** RegularExpression Id. */
  int RBRACKET = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int COLON = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int CMP_GT = 35;
  /** RegularExpression Id. */
  int CMP_LT = 36;
  /** RegularExpression Id. */
  int CMP_LE = 37;
  /** RegularExpression Id. */
  int CMP_GE = 38;
  /** RegularExpression Id. */
  int QMARK = 39;
  /** RegularExpression Id. */
  int CMP_NE = 40;
  /** RegularExpression Id. */
  int CMP_EQ = 41;
  /** RegularExpression Id. */
  int PLUS = 42;
  /** RegularExpression Id. */
  int MINUS = 43;
  /** RegularExpression Id. */
  int BOOL_OR = 44;
  /** RegularExpression Id. */
  int BOOL_AND = 45;
  /** RegularExpression Id. */
  int BOOL_XOR = 46;
  /** RegularExpression Id. */
  int BIT_OR = 47;
  /** RegularExpression Id. */
  int BIT_AND = 48;
  /** RegularExpression Id. */
  int BIT_XOR = 49;
  /** RegularExpression Id. */
  int BIT_NOT = 50;
  /** RegularExpression Id. */
  int SHIFT_LEFT = 51;
  /** RegularExpression Id. */
  int SHIFT_RIGHT = 52;
  /** RegularExpression Id. */
  int EXCLMATION_MARK = 53;
  /** RegularExpression Id. */
  int ARRAY_KEY = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"WITH\"",
    "\"AND\"",
    "\"OR\"",
    "\"XOR\"",
    "\"NOT\"",
    "\"AS\"",
    "<INTEGER_LITERAL>",
    "<HEX_LITERAL>",
    "<HEX_DIGIT>",
    "<REAL_LITERAL>",
    "<EXPONENT>",
    "<SIMPLE_STRING_LITERAL>",
    "<DOUBLE_STRING_LITERAL>",
    "<ESCAPED_CHAR>",
    "<BINARY_LITERAL>",
    "<SIMPLE_ID>",
    "<LETTER>",
    "<DIGIT>",
    "<NOT_RBRACE>",
    "<COMPLEX_ID>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"?\"",
    "\"<>\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"&&\"",
    "\"^^\"",
    "\"|\"",
    "\"&\"",
    "\"^\"",
    "\"~\"",
    "\"<<\"",
    "\">>\"",
    "\"!\"",
    "\"=>\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
