/* Generated By:JavaCC: Do not edit this line. Parser.java */
package de.weinzierlstefan.expressionparser.parser;

import java.util.*;

public class Parser implements ParserConstants {
  public void dummy() {}

  final public Operation parse() throws ParseException {
        Operation a;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WITH:
    case NOT:
    case INTEGER_LITERAL:
    case HEX_LITERAL:
    case REAL_LITERAL:
    case SIMPLE_STRING_LITERAL:
    case DOUBLE_STRING_LITERAL:
    case BINARY_LITERAL:
    case SIMPLE_ID:
    case COMPLEX_ID:
    case LPAREN:
    case LBRACKET:
    case PLUS:
    case MINUS:
    case BIT_NOT:
    case EXCLMATION_MARK:
      a = expression();
      jj_consume_token(0);
                                          {if (true) return a;}
      break;
    case 0:
      jj_consume_token(0);
                                                                  {if (true) return null;}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Operation expression() throws ParseException {
        Operation a;
    a = conditionalExpression();
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation conditionalExpression() throws ParseException {
        Operation a;
        Operation b;
        Operation c;
    a = bitopExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QMARK:
      jj_consume_token(QMARK);
      b = expression();
      jj_consume_token(COLON);
      c = expression();
                                                                a=new Operation(Operation.TERNARY, a, b, c);
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation bitopExpression() throws ParseException {
        Operation a = null;
        Operation b;
    a = compareExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BIT_OR:
    case BIT_AND:
    case BIT_XOR:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BIT_AND:
        jj_consume_token(BIT_AND);
        b = bitopExpression();
                                                  a=new Operation(Operation.BIT_AND, a, b);
        break;
      case BIT_OR:
        jj_consume_token(BIT_OR);
        b = bitopExpression();
                                                  a=new Operation(Operation.BIT_OR, a, b);
        break;
      case BIT_XOR:
        jj_consume_token(BIT_XOR);
        b = bitopExpression();
                                                  a=new Operation(Operation.BIT_XOR, a, b);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation compareExpression() throws ParseException {
        Operation a = null;
        Operation b;
    a = boolExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CMP_GT:
    case CMP_LT:
    case CMP_LE:
    case CMP_GE:
    case CMP_NE:
    case CMP_EQ:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CMP_EQ:
        jj_consume_token(CMP_EQ);
        b = compareExpression();
                                                                  a=new Operation(Operation.CMP_EQ, a, b);
        break;
      case CMP_NE:
        jj_consume_token(CMP_NE);
        b = compareExpression();
                                                          a=new Operation(Operation.CMP_NE, a, b);
        break;
      case CMP_LT:
        jj_consume_token(CMP_LT);
        b = compareExpression();
                                                                  a=new Operation(Operation.CMP_LT, a, b);
        break;
      case CMP_LE:
        jj_consume_token(CMP_LE);
        b = compareExpression();
                                                          a=new Operation(Operation.CMP_LE, a, b);
        break;
      case CMP_GT:
        jj_consume_token(CMP_GT);
        b = compareExpression();
                                                                  a=new Operation(Operation.CMP_GT, a, b);
        break;
      case CMP_GE:
        jj_consume_token(CMP_GE);
        b = compareExpression();
                                                          a=new Operation(Operation.CMP_GE, a, b);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation boolExpression() throws ParseException {
        Operation a = null;
        Operation b;
    a = shiftExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AND:
    case OR:
    case XOR:
    case BOOL_OR:
    case BOOL_AND:
    case BOOL_XOR:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case BOOL_AND:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case BOOL_AND:
          jj_consume_token(BOOL_AND);
          break;
        case AND:
          jj_consume_token(AND);
          break;
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = boolExpression();
                                                                          a=new Operation(Operation.BOOL_AND, a, b);
        break;
      case OR:
      case BOOL_OR:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case BOOL_OR:
          jj_consume_token(BOOL_OR);
          break;
        case OR:
          jj_consume_token(OR);
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = boolExpression();
                                                                          a=new Operation(Operation.BOOL_OR, a, b);
        break;
      case XOR:
      case BOOL_XOR:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case BOOL_XOR:
          jj_consume_token(BOOL_XOR);
          break;
        case XOR:
          jj_consume_token(XOR);
          break;
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        b = boolExpression();
                                                                          a=new Operation(Operation.BOOL_XOR, a, b);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation shiftExpression() throws ParseException {
        Operation a = null;
        Operation b;
    a = additiveExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SHIFT_LEFT:
    case SHIFT_RIGHT:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SHIFT_LEFT:
        jj_consume_token(SHIFT_LEFT);
        b = shiftExpression();
                                                                  a = new Operation(Operation.SHIFT_LEFT, a, b);
        break;
      case SHIFT_RIGHT:
        jj_consume_token(SHIFT_RIGHT);
        b = shiftExpression();
                                                                  a = new Operation(Operation.SHIFT_RIGHT, a, b);
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation additiveExpression() throws ParseException {
        Operation a;
        Operation b;
    a = multiplicativeExpression();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[13] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        b = multiplicativeExpression();
                                                                  a = new Operation(Operation.ADD, a, b);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        b = multiplicativeExpression();
                                                                  a = new Operation(Operation.SUB, a, b);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation multiplicativeExpression() throws ParseException {
        Operation a;
        Operation b;
    a = unaryExpression1();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 55:
      case 56:
      case 57:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 55:
        jj_consume_token(55);
        b = unaryExpression1();
                                                      a = new Operation(Operation.MUL, a, b);
        break;
      case 56:
        jj_consume_token(56);
        b = unaryExpression1();
                                                      a = new Operation(Operation.DIV, a, b);
        break;
      case 57:
        jj_consume_token(57);
        b = unaryExpression1();
                                                          a = new Operation(Operation.MOD, a, b);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          {if (true) return a;}
    throw new Error("Missing return statement in function");
  }

  final public Operation unaryExpression1() throws ParseException {
    Operation a;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      jj_consume_token(MINUS);
      a = unaryExpression1();
                                               {if (true) return new Operation(Operation.NEGATE, a);}
      break;
    case PLUS:
      jj_consume_token(PLUS);
      a = unaryExpression1();
                                               {if (true) return a;}
      break;
    case WITH:
    case NOT:
    case INTEGER_LITERAL:
    case HEX_LITERAL:
    case REAL_LITERAL:
    case SIMPLE_STRING_LITERAL:
    case DOUBLE_STRING_LITERAL:
    case BINARY_LITERAL:
    case SIMPLE_ID:
    case COMPLEX_ID:
    case LPAREN:
    case LBRACKET:
    case BIT_NOT:
    case EXCLMATION_MARK:
      a = unaryExpression2();
                                               {if (true) return a;}
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Operation unaryExpression2() throws ParseException {
        Operation a;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BIT_NOT:
      jj_consume_token(BIT_NOT);
      a = unaryExpression2();
                                                                                  {if (true) return new Operation(Operation.BIT_NOT, a);}
      break;
    case NOT:
    case EXCLMATION_MARK:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
        jj_consume_token(NOT);
        break;
      case EXCLMATION_MARK:
        jj_consume_token(EXCLMATION_MARK);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      a = unaryExpression2();
                                                                      {if (true) return new Operation(Operation.BOOL_NOT, a);}
      break;
    case WITH:
    case INTEGER_LITERAL:
    case HEX_LITERAL:
    case REAL_LITERAL:
    case SIMPLE_STRING_LITERAL:
    case DOUBLE_STRING_LITERAL:
    case BINARY_LITERAL:
    case SIMPLE_ID:
    case COMPLEX_ID:
    case LPAREN:
    case LBRACKET:
      a = element();
                                                                                                                                  {if (true) return a;}
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Operation complexElement() throws ParseException {
        Operation a;
        Token t;
    if (jj_2_1(3)) {
      a = with();
                                                                                                          {if (true) return a;}
    } else if (jj_2_2(3)) {
      a = function();
                                                                                          {if (true) return a;}
    } else if (jj_2_3(2)) {
      t = jj_consume_token(SIMPLE_ID);
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
                                                          {if (true) return new Operation(Operation.FUNCTION_CALL, t.toString());}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SIMPLE_ID:
        t = jj_consume_token(SIMPLE_ID);
                                                                          {if (true) return new Operation(Operation.VARIABLE, t.toString());}
        break;
      case COMPLEX_ID:
        t = jj_consume_token(COMPLEX_ID);
                                                                          {if (true) return new Operation(Operation.VARIABLE_ESC, t.toString());}
        break;
      case LPAREN:
        jj_consume_token(LPAREN);
        a = expression();
        jj_consume_token(RPAREN);
                                                                  {if (true) return a;}
        break;
      case LBRACKET:
        a = arrayExpression();
                                                          {if (true) return a;}
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Operation complexElement2() throws ParseException {
  Operation a;
  List<Operation> operationList;
    if (jj_2_4(2)) {
      a = complexElement();
      operationList = suffixExpressionList();
                                                                                       operationList.add(0, a); {if (true) return new Operation(Operation.SUFFIXED, operationList);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WITH:
      case SIMPLE_ID:
      case COMPLEX_ID:
      case LPAREN:
      case LBRACKET:
        a = complexElement();
                                  {if (true) return a;}
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public List<Operation> suffixExpressionList() throws ParseException {
        List<Operation> operationList = new ArrayList<Operation>();
        Operation a;
    label_3:
    while (true) {
      a = suffixExpression();
                                          operationList.add(a);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LBRACKET:
      case DOT:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_3;
      }
    }
                  {if (true) return operationList;}
    throw new Error("Missing return statement in function");
  }

  final public Operation suffixExpression() throws ParseException {
        Operation a;
        Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      a = arrayExpression();
                                          {if (true) return a;}
      break;
    default:
      jj_la1[23] = jj_gen;
      if (jj_2_5(2)) {
        jj_consume_token(DOT);
        t = jj_consume_token(SIMPLE_ID);
                                                  a = new Operation(Operation.SIMPLE_NAME_SUFFIX, t.toString());
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DOT:
          jj_consume_token(DOT);
          t = jj_consume_token(COMPLEX_ID);
                                 a= new Operation(Operation.COMPLEX_NAME_SUFFIX, t.toString());
          break;
        default:
          jj_la1[24] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Operation arrayExpression() throws ParseException {
        List<Operation> operationList = new ArrayList<Operation>();
        Operation a;
    jj_consume_token(LBRACKET);
    a = arrayEntry();
                                                                          operationList.add(a);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_4;
      }
      jj_consume_token(COMMA);
      a = arrayEntry();
                                                  operationList.add(a);
    }
    jj_consume_token(RBRACKET);
          {if (true) return new Operation(Operation.ARRAY_LIST, operationList);}
    throw new Error("Missing return statement in function");
  }

  final public Operation arrayEntry() throws ParseException {
        Operation a;
        Operation b=null;
    a = expression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ARRAY_KEY:
      jj_consume_token(ARRAY_KEY);
      b = expression();
      break;
    default:
      jj_la1[26] = jj_gen;
      ;
    }
          {if (true) return new Operation(Operation.ARRAY_ENTRY, a, b);}
    throw new Error("Missing return statement in function");
  }

  final public Operation element() throws ParseException {
    Token t;
    Operation a;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      t = jj_consume_token(INTEGER_LITERAL);
                                                  {if (true) return new Operation(Operation.INTEGER_LITERAL, t.toString());}
      break;
    case REAL_LITERAL:
      t = jj_consume_token(REAL_LITERAL);
                                                          {if (true) return new Operation(Operation.REAL_LITERAL, t.toString());}
      break;
    case HEX_LITERAL:
      t = jj_consume_token(HEX_LITERAL);
                                                                          {if (true) return new Operation(Operation.HEX_LITERAL, t.toString());}
      break;
    case BINARY_LITERAL:
      t = jj_consume_token(BINARY_LITERAL);
                                                          {if (true) return new Operation(Operation.BINARY_LITERAL, t.toString());}
      break;
    case SIMPLE_STRING_LITERAL:
      t = jj_consume_token(SIMPLE_STRING_LITERAL);
                                          {if (true) return new Operation(Operation.SIMPLE_STRING_LITERAL, t.toString());}
      break;
    case DOUBLE_STRING_LITERAL:
      t = jj_consume_token(DOUBLE_STRING_LITERAL);
                                          {if (true) return new Operation(Operation.DOUBLE_STRING_LITERAL, t.toString());}
      break;
    case WITH:
    case SIMPLE_ID:
    case COMPLEX_ID:
    case LPAREN:
    case LBRACKET:
      a = complexElement();
                                                  {if (true) return a;}
      break;
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Operation function() throws ParseException {
        List<Operation> operationList = new ArrayList<Operation>();
        Operation a;
        Token t;
    t = jj_consume_token(SIMPLE_ID);
    jj_consume_token(LPAREN);
    a = expression();
                                                                          operationList.add(a);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      a = expression();
                                                  operationList.add(a);
    }
    jj_consume_token(RPAREN);
          {if (true) return new Operation(Operation.FUNCTION_CALL, t.toString(), operationList);}
    throw new Error("Missing return statement in function");
  }

  final public Operation with() throws ParseException {
        List<Operation> operationList = new ArrayList<Operation>();
        Operation a;
        Token t;
    jj_consume_token(WITH);
    jj_consume_token(LPAREN);
    label_6:
    while (true) {
      if (jj_2_6(6)) {
        ;
      } else {
        break label_6;
      }
      a = expression();
      jj_consume_token(AS);
      t = jj_consume_token(SIMPLE_ID);
      jj_consume_token(COMMA);
                  operationList.add(new Operation(Operation.AS, t.toString(), a));
    }
    a = expression();
    jj_consume_token(RPAREN);
                operationList.add(a);
                {if (true) return new Operation(Operation.WITH, operationList);}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(CMP_GE)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(CMP_GT)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(CMP_LE)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(CMP_LT)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_11()) return true;
    if (jj_scan_token(AS)) return true;
    if (jj_scan_token(SIMPLE_ID)) return true;
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(CMP_NE)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(CMP_EQ)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_28() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_32()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(WITH)) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_6()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_11()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_27()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(BIT_XOR)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(BIT_OR)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(BIT_AND)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_8() {
    if (jj_scan_token(SIMPLE_ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_11()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_71()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(HEX_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_scan_token(DOUBLE_STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_scan_token(SIMPLE_STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_scan_token(BINARY_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(QMARK)) return true;
    if (jj_3R_11()) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(REAL_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) {
    jj_scanpos = xsp;
    if (jj_3R_70()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_scan_token(ARRAY_KEY)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_3R_20()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_11()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_73()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_72()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(SIMPLE_ID)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    Token xsp;
    if (jj_3R_16()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_16()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_9()) return true;
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_11()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3R_12()) {
    jj_scanpos = xsp;
    if (jj_3R_13()) {
    jj_scanpos = xsp;
    if (jj_3R_14()) {
    jj_scanpos = xsp;
    if (jj_3R_15()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(COMPLEX_ID)) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(SIMPLE_ID)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(SIMPLE_ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3R_61() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) return true;
    }
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(BIT_NOT)) return true;
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(56)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(55)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(57)) return true;
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_49()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(SHIFT_RIGHT)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(SHIFT_LEFT)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_45()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_46()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(8)) return true;
    }
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(7)) return true;
    }
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(45)) {
    jj_scanpos = xsp;
    if (jj_scan_token(6)) return true;
    }
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_40()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) jj_scanpos = xsp;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[29];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x231b5a21,0x0,0x0,0x0,0x0,0x0,0x40,0x80,0x100,0x1c0,0x1c0,0x0,0x0,0x0,0x0,0x0,0x0,0x231b5a20,0x200,0x231b5a20,0x23100000,0x23100020,0x20000000,0x20000000,0x0,0x0,0x0,0x231b5820,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x240c00,0x80,0x38000,0x38000,0x378,0x378,0x2000,0x1000,0x4000,0x7000,0x7000,0x180000,0x180000,0xc00,0xc00,0x3800000,0x3800000,0x240c00,0x200000,0x240000,0x0,0x0,0x4,0x0,0x4,0x2,0x400000,0x0,0x2,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[6];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 29; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[58];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 29; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 58; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 6; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
